block/systemsim_bd: Forward port to 3.16
In db2a144be block_device_operations->release() should return void
the release callback was changed to return void. Update our driver to
avoid the following waring:

drivers/block/systemsim_bd.c:233:7: warning: initialization from
incompatible pointer type [enabled by default]
       .release  = systemsim_bd_release,

In b4f42e283 block: remove struct request buffer member the request
member was removed, and old drivers were converted to use a accessor
bio_data(req->bio). Do the same to avoid this error:

drivers/block/systemsim_bd.c: In function ‘do_systemsim_bd_request’:
drivers/block/systemsim_bd.c:146:15: error: ‘struct request’ has no member
named ‘buffer’
            req->buffer, blk_rq_pos(req),
               ^
drivers/block/systemsim_bd.c:151:16: error: ‘struct request’ has no member
named ‘buffer’
             req->buffer, blk_rq_pos(req),
                ^

Signed-off-by: Joel Stanley <joel@jms.id.au>