powerpc/module_64: Fix error in debug printf
When DEBUG is set to 1:

 arch/powerpc/kernel/module_64.c: In function ‘get_stubs_size’:
 arch/powerpc/kernel/module_64.c:285:11: error: format ‘%lu’ expects
    argument of type ‘long unsigned int’, but argument 3 has type
    ‘long long unsigned int’ [-Werror=format=]
           sechdrs[i].sh_size / sizeof(Elf64_Rela));
           ^

Signed-off-by: Joel Stanley <joel@jms.id.au>